###############################################################
# Parse dataframe objects from the NodeMCU webserver.         #
# Data generated by Kaifa MA304H3E AMS meter.                 #
#                                                             #
# The resulting parsed HTML table is a list containing        #
# one dataframe object, (one list element).                   #
#                                                             #
# Extracted values from the dataframe are saved to file       #
# on disk.                                                    #
###############################################################

import pandas as pd
import time
import urllib2

#folderName = "C:\\Users\\helge\\Desktop\\python\\logs\\"
folderName = "C:\\Users\\HelgeN550JK\\Desktop\\AMS\\python\\logs\\"

def main(folderName):
    # Initialize variable for max iterations to run
    num_iter = 0
    while num_iter < 250000:
        rows = columns = 0
        try:
            # Skip the first six rows of the webpage table
            dfs = pd.read_html('http://192.168.10.134', skiprows = 6)
            # rows, columns expected 21, 2
            rows, columns = dfs[0].shape
            # rows = len(dfs[0].index)
            # columns = len(dfs[0].columns)
            # Use date as file name
            fName = folderName + dfs[0].iloc[0][1] + ".txt"
            if rows == 21 and columns == 2:
                with open(fName, "a") as fp:
                    # Only write the first 19 rows to file
                    for z in range(0, 18, 1):
                        u = dfs[0].iloc[z][1]
                        fp.write(u + ",")
                    v = dfs[0].iloc[18][1]
                    fp.write(v + "\n")
                num_iter += 1
                print("Lines written to disk: %2s" % num_iter)
                time.sleep(10)
        except urllib2.URLError as errorA:
            print "Link feil:\n", errorA, "\n"
            time.sleep(10)
        except:
            print "Noe annet gikk galt. Beklager."
            time.sleep(10)

if __name__ == '__main__':
  main(folderName)
